[workspace]
resolver = "2"
members = [
    "restaurant_registry",
    "order",
    "payment",
    "loyalty_token",
    "tests",
]

[workspace.dependencies]
soroban-sdk = { version = "22.0.0", features = ["alloc"] }
